- android/src/main/CMakeLists.txt
- cpp/llama.cpp
- cpp/log.h
- scripts/bootstrap.sh
- scripts/llama.cpp.patch
- scripts/log.h.patch
Currently the logs always pipe to /dev/null on Android, and it's difficult to change it depending on the device, so I use a patch to simply change the logs by use `android/log.h`.
> feat(android): enable logging (llama.cpp, log.h) on debug mode

- android/src/main/CMakeLists.txt
- android/src/main/java/com/rnllama/LlamaContext.java
This seems make PP / TG faster on Qualcomm devices.
> feat(android): enable armv8.2-a+fp16+dotprod

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- android/src/newarch/java/com/rnllama/RNLlamaModule.java
- android/src/oldarch/java/com/rnllama/RNLlamaModule.java
- ios/RNLlama.mm
- ios/RNLlamaContext.h
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
- src/index.ts
Use full session size if <= 0 or > session size.
> feat: add size option for saveSession

- example/src/App.tsx
Added the MIME type to filter model files. 
I'm not sure about the [UTI](https://developer.apple.com/documentation/uniformtypeidentifiers/system-declared_uniform_type_identifiers) for Apple (unable to test), but `public.data` seems correct.
Let me know if this works for iOS.
> feat: filter GGUF model files

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- android/src/newarch/java/com/rnllama/RNLlamaModule.java
- android/src/oldarch/java/com/rnllama/RNLlamaModule.java
- cpp/rn-llama.hpp
- docs/API/README.md
- docs/API/classes/LlamaContext.md
- docs/API/classes/SchemaGrammarConverter.md
- example/ios/Podfile.lock
- example/package.json
- example/src/App.tsx
- example/src/Bubble.tsx
- example/yarn.lock
- ios/RNLlama.mm
- ios/RNLlamaContext.h
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
- src/index.ts
Closes #8.
Pixel 6 results (CPU) in Phi-2 Q4_0:
> feat: add bench method

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- docs/API/README.md
- docs/API/classes/LlamaContext.md
- docs/API/classes/SchemaGrammarConverter.md
- example/src/App.tsx
- ios/RNLlama.mm
- ios/RNLlamaContext.h
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
- src/index.ts
Put model meta / size / n_params / desc into the context.
> feat: add model details in context

- src/index.ts
Just a simple fix that reuses code from `initLlama` for `loadSession` when using `file://` URI's.
> fix(android): loadSession not taking paths with file://

- cpp/ggml-quants.c
- cpp/ggml.c
- cpp/llama.cpp
- cpp/llama.h
> feat: sync llama.cpp

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- ios/RNLlamaContext.mm
> fix: not init sampling before get embedding

- README.md
- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- android/src/newarch/java/com/rnllama/RNLlamaModule.java
- android/src/oldarch/java/com/rnllama/RNLlamaModule.java
- cpp/rn-llama.hpp
- docs/API/README.md
- docs/API/classes/LlamaContext.md
- docs/API/classes/SchemaGrammarConverter.md
- example/ios/.xcode.env.local
- example/ios/Podfile.lock
- example/package.json
- example/src/App.tsx
- example/yarn.lock
- ios/RNLlama.mm
- ios/RNLlamaContext.h
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
- src/__tests__/chat.test.ts
- src/chat.ts
- src/index.ts
Support convert OpenAI API compatible message (`[{ role, content }, ...]` and then [`llama_chat_apply_template`](https://github.com/ggerganov/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template).
- New field: `context.model.isChatTemplateSupported`
- `context.completion(...)`: Add `messages: RNLlamaOAICompatibleMessage[]` in params
- It is not recommended to use messages if the model is not supported chat template
- New util: `context.getFormattedChat(messages: RNLlamaOAICompatibleMessage[]): string)`
- If the chat template is not supported in model, we will fallback to use `chatml` as format
- `context.completion` also uses it to convert messages to prompt
> feat: support chat format

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- android/src/newarch/java/com/rnllama/RNLlamaModule.java
- android/src/oldarch/java/com/rnllama/RNLlamaModule.java
- cpp/rn-llama.hpp
- docs/API/README.md
- docs/API/classes/LlamaContext.md
- docs/API/classes/SchemaGrammarConverter.md
- example/src/App.tsx
- ios/RNLlama.mm
- ios/RNLlamaContext.h
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
- src/index.ts
Currently if we just want to get metadata from a GGUF file, we can initialize context with `vocab_only` and get metadata then release, but it not fast enough (~300ms).
This PR added a static `modelInfo(model: string)` for get metadata from a GGUF file, it can get metadata by ~30ms.
TODO:
> feat: add static method for read model info from gguf

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- android/src/newarch/java/com/rnllama/RNLlamaModule.java
- android/src/oldarch/java/com/rnllama/RNLlamaModule.java
- cpp/rn-llama.hpp
- docs/API/README.md
- docs/API/classes/LlamaContext.md
- docs/API/classes/SchemaGrammarConverter.md
- example/src/App.tsx
- ios/RNLlama.mm
- ios/RNLlamaContext.h
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
- src/index.ts
- Expose `pooling_type` / `embd_normalize ` params in `initLlama`
- Allow custom `embd_normalize` param in `context.embedding` method
- Add encoder-decoder model check (it not supported computing embeddings)
- `llama_rn_context::getEmbedding`: Take `llama_pooling_type(ctx)` instead of from params
> feat: update embedding method

- README.md
As discussed on #85 the app crashes when calling `initLlama` without first calling `loadLlamaModelInfo`. I found this in the example applications but it's not clear in the README example.
> Update code example to load the model info before initializing context

- cpp/common.cpp
- cpp/common.h
- scripts/common.cpp.patch
- scripts/common.h.patch
> fix(cpp): progress_callback patch

- android/src/main/CMakeLists.txt
This PR adds `-DLM_GGML_USE_CPU_AARCH64` compile definition to Android CMake build, which in turn enables runtime tensor repacking optimization for Q4_0 quantization on ARM64.
The screenshot from PocketPal's benchmarking before/after setting `-DLM_GGML_USE_CPU_AARCH64`:
> feat(android): enable runtime repacking for Q4_0 quantization on aarch64

- cpp/rn-llama.hpp
Replaces `printf` with `__android_log_write` for Android compatibility in rn-llama.hpp
> fix(log): implement Android logging in rn-llama.hpp as opposed to printf

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/jni.cpp
- cpp/rn-llama.hpp
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
This PR introduces the following changes:
- Expose n_ubatch: Allows applications/users to modify `n_ubatch` as needed.
- Dynamic ntokens for bench: Previously, the ntokens value for bench was hardcoded to **512**. This is now dynamically set to min(pp, n_ubatch), allowing more flexibility for benchmarking scenarios.
> feat: expose n_ubatch and dynamically adjust ntokens for bench

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- android/src/newarch/java/com/rnllama/RNLlamaModule.java
- android/src/oldarch/java/com/rnllama/RNLlamaModule.java
- docs/API/README.md
- docs/API/classes/LlamaContext.md
- docs/API/classes/SchemaGrammarConverter.md
- docs/API/classes/SchemaGrammarConverterBuiltinRule.md
- example/src/App.tsx
- ios/RNLlama.h
- ios/RNLlama.mm
- ios/RNLlamaContext.h
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
- src/index.ts
Implement two export functions:
- `toggleNativeLog(enabled: boolean)`
- `addNativeLogListener(listener: (level: string, message: string) => void): { remove: () => void }`
TODO:
> feat: listen native logs

- android/src/main/jni.cpp
- example/src/App.tsx
- ios/RNLlamaContext.mm
Find NULL token (image chunk) in the tokens and resize the array to the index of the null token. Fix crash when load a saved text/image conversation.
> fix(mtmd): state load and save

- android/src/main/java/com/rnllama/LlamaContext.java
- android/src/main/java/com/rnllama/RNLlama.java
- android/src/main/jni.cpp
- android/src/newarch/java/com/rnllama/RNLlamaModule.java
- android/src/oldarch/java/com/rnllama/RNLlamaModule.java
- cpp/rn-llama.cpp
- cpp/rn-llama.h
- example/src/App.tsx
- ios/RNLlama.mm
- ios/RNLlamaContext.h
- ios/RNLlamaContext.mm
- src/NativeRNLlama.ts
- src/index.ts
Tokenize result in gemma-3-4b-it-Q4_K_M and mmproj-model-f16:
```
LOG  Formatted: {"additional_stops": [], "chat_format": 0, "grammar": "", "grammar_lazy": false, "grammar_triggers": [], "has_image": true, "image_paths": ["data:image/jpeg;base64,..."], "preserved_tokens": [], "prompt": "<start_of_turn>user
This is a conversation between user and assistant, a friendly chatbot.
what is this
<__image__><end_of_turn>
<start_of_turn>model
", "type": "jinja"} 
Tokenize: {"bitmap_hashes": ["14998100942951667560"], "chunk_pos": [0, 23, 279], "chunk_pos_images": [23], "has_images": true, "tokens": [2, 105, 2364, 107, 2094, 563, 496, 12309, 1534, 2430, 532, 16326, 236764, 496, 10841, 110130, 236761, 110, 14070, 563, 672, 107, 255999, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, …
```
> feat: support tokenize image messages

- cpp/rn-mtmd.hpp
Partial KV cache removal (`llama_memory_seq_rm`) may fail on non-Transformer multimodal architectures (e.g. LFM2-VL). This change adds a fallback by full cache clear, ie `llama_memory_clear`.
Closes #187
> fx: handle partial kv clear failure on non-Transformer models (eg LFM2-VL)
